name: flutter drive

on: [push, pull_request]

jobs:
  drive:
    strategy:
      matrix:
        device:
          - "iPhone 14"
          # - "iPad Air (5th generation)"
      fail-fast: false
    runs-on: macOS-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set latest Xcode version
        run: |
          echo "Available Xcode versions:"
          XCODE_PATH=$(ls /Applications | grep Xcode | sort -V | tail -n 1)
          echo "Selected Xcode version: $XCODE_PATH"
          sudo xcode-select -switch /Applications/$XCODE_PATH/Contents/Developer

      - name: "Install flutter"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.3'
          channel: 'stable'
          cache: true
          cache-key: flutter-3.10.3
          cache-path: ${{ runner.tool_cache }}/flutter-3.10.3

      - name: Cache Dart SDK
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-dart-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-dart-
      - name: flutter pub get
        run: flutter pub get
    
      - name: Check CocoaPods installation
        run: |
          if ! command -v pod &> /dev/null
          then
            sudo gem install cocoapods
          fi

      - name: Cache CocoaPods
        uses: actions/cache@v2
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install Pods
        if: steps.cache.outputs.cache-hit != 'true'
        run: cd ios && pod install

      - name: "Start Simulator"
        run: |
          UUID=$(xcrun simctl list devices | grep -v "Unavailable" | grep -v "unavailable" | sed -E 's/ \(([A-Z0-9\-]+)\) / -- (\1) /g' | grep "${{ matrix.device }} -- " | awk -F '[()]' '{print $(NF-3)}')
          echo $UUID
          echo "UUID=$UUID" >> $GITHUB_ENV
          xcrun simctl boot $UUID

      - name: "Run Flutter Driver tests"
        run: "flutter drive --target=test_driver/app.dart"
        # run: sh flutter_drive.sh $UUID

      - name: "Shutdown Simulator"
        if: always()
        run: xcrun simctl shutdown $UUID
